//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using System;
    using OperatorManagementDL.Models;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(TransactionMD))]
    public partial class Tbl_Transaction
    {
        public int Fld_Transaction_Id { get; set; }
        public System.DateTime Fld_Transaction_Date { get; set; }
        public int Fld_Sim_FromSimId { get; set; }
        public int Fld_Sim_ToSimId { get; set; }
        public int Fld_TransactionType_Id { get; set; }
        public System.TimeSpan Fld_Transaction_Start { get; set; }
        public Nullable<System.TimeSpan> Fld_Transaction_End { get; set; }
    
        public virtual Tbl_Sim Tbl_Sim { get; set; }
        public virtual Tbl_Sim Tbl_Sim1 { get; set; }
        public virtual Tbl_TransactionType Tbl_TransactionType { get; set; }
    }
}
