//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using OperatorManagementDL.Models;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;

    [MetadataType(typeof(SimMD))]
    public partial class Tbl_Sim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sim()
        {
            this.Tbl_Transaction = new HashSet<Tbl_Transaction>();
            this.Tbl_Transaction1 = new HashSet<Tbl_Transaction>();
        }
    
        public int Fld_Sim_Id { get; set; }
        public string Fld_Sim_Number { get; set; }
        public int Fld_Person_Id { get; set; }
    
        public virtual Tbl_Person Tbl_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaction> Tbl_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaction> Tbl_Transaction1 { get; set; }
        public virtual Tbl_Wallet Tbl_Wallet { get; set; }
    }
}
