//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cost
    {
        public int Fld_Cost_Id { get; set; }
        public decimal Fld_Cost_Value { get; set; }
        public string Fld_Cost_Description { get; set; }
    
        public virtual Tbl_TransactionType Tbl_TransactionType { get; set; }
    }
}
