//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sim()
        {
            this.Tbl_ChargeLog = new HashSet<Tbl_ChargeLog>();
            this.Tbl_Transaction = new HashSet<Tbl_Transaction>();
            this.Tbl_Transaction1 = new HashSet<Tbl_Transaction>();
        }
    
        public int Fld_Sim_Id { get; set; }
        public string Fld_Sim_Number { get; set; }
        public int Fld_Person_Id { get; set; }
        public bool Fld_Sim_IsActive { get; set; }
        public int Fld_SimType_Id { get; set; }
        public bool Fld_Sim_IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ChargeLog> Tbl_ChargeLog { get; set; }
        public virtual Tbl_Person Tbl_Person { get; set; }
        public virtual Tbl_SimType Tbl_SimType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaction> Tbl_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Transaction> Tbl_Transaction1 { get; set; }
        public virtual Tbl_Wallet Tbl_Wallet { get; set; }
    }
}
