//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_UserSession = new HashSet<Tbl_UserSession>();
            this.Tbl_Role = new HashSet<Tbl_Role>();
        }
    
        public int Fld_User_Id { get; set; }
        public string Fld_User_Username { get; set; }
        public string Fld_User_Password { get; set; }
        public string Fld_User_Email { get; set; }
        public bool Fld_User_IsLocked { get; set; }
        public Nullable<int> Fld_Person_PersonId { get; set; }
    
        public virtual Tbl_Person Tbl_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserSession> Tbl_UserSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Role> Tbl_Role { get; set; }
    }
}
