//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserSession
    {
        public string Fld_UserSession_SessionId { get; set; }
        public int Fld_User_UserId { get; set; }
        public System.DateTime Fld_UserSession_DateTime { get; set; }
    
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
