//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorManagementDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Person()
        {
            this.Tbl_Sim = new HashSet<Tbl_Sim>();
        }
    
        public int Fld_Person_Id { get; set; }
        public string Fld_Person_Fname { get; set; }
        public string Fld_Person_Lname { get; set; }
        public string Fld_Person_NationCode { get; set; }
        public bool Fld_Person_IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sim> Tbl_Sim { get; set; }
    }
}
