USE [master]
GO
CREATE DATABASE [OperatorManagementDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OperatorManagementDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\OperatorManagementDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OperatorManagementDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\OperatorManagementDB_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [OperatorManagementDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OperatorManagementDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OperatorManagementDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OperatorManagementDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OperatorManagementDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OperatorManagementDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OperatorManagementDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET RECOVERY FULL 
GO
ALTER DATABASE [OperatorManagementDB] SET  MULTI_USER 
GO
ALTER DATABASE [OperatorManagementDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OperatorManagementDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OperatorManagementDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OperatorManagementDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OperatorManagementDB] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'OperatorManagementDB', N'ON'
GO
USE [OperatorManagementDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_ChargeLog](
	[Fld_ChargeLog_Id] [int] IDENTITY(1,1) NOT NULL,
	[Fld_Sim_SimId] [int] NOT NULL,
	[Fld_ChargeLog_Date] [datetime] NOT NULL,
	[Fld_ChargeLog_Value] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Tbl_ChargeLog] PRIMARY KEY CLUSTERED 
(
	[Fld_ChargeLog_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Cost](
	[Fld_Cost_Id] [int] NOT NULL,
	[Fld_Cost_Value] [decimal](10, 2) NOT NULL,
	[Fld_Cost_Description] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Tbl_Cost_1] PRIMARY KEY CLUSTERED 
(
	[Fld_Cost_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Person](
	[Fld_Person_Id] [int] IDENTITY(1,1) NOT NULL,
	[Fld_Person_Fname] [nvarchar](50) NOT NULL,
	[Fld_Person_Lname] [nvarchar](150) NOT NULL,
	[Fld_Person_NationCode] [nvarchar](50) NOT NULL,
	[Fld_Person_IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Tbl_Person] PRIMARY KEY CLUSTERED 
(
	[Fld_Person_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_Tbl_Person_NationCode] UNIQUE NONCLUSTERED 
(
	[Fld_Person_NationCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Role](
	[Fld_Role_Id] [int] IDENTITY(1,1) NOT NULL,
	[Fld_Role_Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Tbl_Role] PRIMARY KEY CLUSTERED 
(
	[Fld_Role_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Sim](
	[Fld_Sim_Id] [int] IDENTITY(1,1) NOT NULL,
	[Fld_Sim_Number] [nvarchar](20) NOT NULL,
	[Fld_Person_Id] [int] NOT NULL,
	[Fld_Sim_IsActive] [bit] NOT NULL,
	[Fld_SimType_Id] [int] NOT NULL,
	[Fld_Sim_IsDeleted] [bit] NOT NULL,
 CONSTRAINT [PK_Tbl_Sim] PRIMARY KEY CLUSTERED 
(
	[Fld_Sim_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_Tbl_Sim_Fld_Sim_Number] UNIQUE NONCLUSTERED 
(
	[Fld_Sim_Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_SimType](
	[Fld_SimType_Id] [int] NOT NULL,
	[Fld_SimType_Value] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Tbl_SimType] PRIMARY KEY CLUSTERED 
(
	[Fld_SimType_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Transaction](
	[Fld_Transaction_Id] [int] IDENTITY(1,1) NOT NULL,
	[Fld_Transaction_Date] [datetime] NOT NULL,
	[Fld_Sim_FromSimId] [int] NOT NULL,
	[Fld_Sim_ToSimId] [int] NOT NULL,
	[Fld_TransactionType_Id] [int] NOT NULL,
	[Fld_Transaction_Duration] [time](7) NULL,
 CONSTRAINT [PK_Tbl_Transaction] PRIMARY KEY CLUSTERED 
(
	[Fld_Transaction_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_TransactionType](
	[Fld_TransactionType_Id] [int] NOT NULL,
	[Fld_TransactionType_Type] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Tbl_TransactionType] PRIMARY KEY CLUSTERED 
(
	[Fld_TransactionType_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_User](
	[Fld_User_Id] [int] IDENTITY(1,1) NOT NULL,
	[Fld_User_Username] [nvarchar](50) NOT NULL,
	[Fld_User_Password] [nvarchar](max) NOT NULL,
	[Fld_User_Email] [nvarchar](100) NOT NULL,
	[Fld_User_IsLocked] [bit] NOT NULL,
	[Fld_Person_PersonId] [int] NULL,
 CONSTRAINT [PK_Tbl_User] PRIMARY KEY CLUSTERED 
(
	[Fld_User_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_UserRole](
	[Fld_User_UserId] [int] NOT NULL,
	[Fld_Role_RoleId] [int] NOT NULL,
 CONSTRAINT [PK_Tbl_UserRole] PRIMARY KEY CLUSTERED 
(
	[Fld_User_UserId] ASC,
	[Fld_Role_RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_UserSession](
	[Fld_UserSession_SessionId] [nvarchar](100) NOT NULL,
	[Fld_User_UserId] [int] NOT NULL,
	[Fld_UserSession_DateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Tbl_UserSession] PRIMARY KEY CLUSTERED 
(
	[Fld_UserSession_SessionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tbl_Wallet](
	[Fld_Wallet_Id] [int] NOT NULL,
	[Fld_Wallet_Balance] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Tbl_Wallet] PRIMARY KEY CLUSTERED 
(
	[Fld_Wallet_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FK_Tbl_Sim_Tbl_Person] ON [dbo].[Tbl_Sim]
(
	[Fld_Person_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FK_Tbl_SimTbl_SimType] ON [dbo].[Tbl_Sim]
(
	[Fld_SimType_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FK_Tbl_Transaction_Tbl_Sim] ON [dbo].[Tbl_Transaction]
(
	[Fld_Sim_FromSimId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FK_Tbl_Transaction_Tbl_Sim1] ON [dbo].[Tbl_Transaction]
(
	[Fld_Sim_ToSimId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FK_Tbl_Transaction_Tbl_TransactionType] ON [dbo].[Tbl_Transaction]
(
	[Fld_TransactionType_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tbl_ChargeLog]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_ChargeLog_Tbl_Sim] FOREIGN KEY([Fld_Sim_SimId])
REFERENCES [dbo].[Tbl_Sim] ([Fld_Sim_Id])
GO
ALTER TABLE [dbo].[Tbl_ChargeLog] CHECK CONSTRAINT [FK_Tbl_ChargeLog_Tbl_Sim]
GO
ALTER TABLE [dbo].[Tbl_Cost]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Cost_Tbl_TransactionType] FOREIGN KEY([Fld_Cost_Id])
REFERENCES [dbo].[Tbl_TransactionType] ([Fld_TransactionType_Id])
GO
ALTER TABLE [dbo].[Tbl_Cost] CHECK CONSTRAINT [FK_Tbl_Cost_Tbl_TransactionType]
GO
ALTER TABLE [dbo].[Tbl_Sim]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Sim_Tbl_Person] FOREIGN KEY([Fld_Person_Id])
REFERENCES [dbo].[Tbl_Person] ([Fld_Person_Id])
GO
ALTER TABLE [dbo].[Tbl_Sim] CHECK CONSTRAINT [FK_Tbl_Sim_Tbl_Person]
GO
ALTER TABLE [dbo].[Tbl_Sim]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_SimTbl_SimType] FOREIGN KEY([Fld_SimType_Id])
REFERENCES [dbo].[Tbl_SimType] ([Fld_SimType_Id])
GO
ALTER TABLE [dbo].[Tbl_Sim] CHECK CONSTRAINT [FK_Tbl_SimTbl_SimType]
GO
ALTER TABLE [dbo].[Tbl_Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Transaction_Tbl_Sim] FOREIGN KEY([Fld_Sim_FromSimId])
REFERENCES [dbo].[Tbl_Sim] ([Fld_Sim_Id])
GO
ALTER TABLE [dbo].[Tbl_Transaction] CHECK CONSTRAINT [FK_Tbl_Transaction_Tbl_Sim]
GO
ALTER TABLE [dbo].[Tbl_Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Transaction_Tbl_Sim1] FOREIGN KEY([Fld_Sim_ToSimId])
REFERENCES [dbo].[Tbl_Sim] ([Fld_Sim_Id])
GO
ALTER TABLE [dbo].[Tbl_Transaction] CHECK CONSTRAINT [FK_Tbl_Transaction_Tbl_Sim1]
GO
ALTER TABLE [dbo].[Tbl_Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Transaction_Tbl_TransactionType] FOREIGN KEY([Fld_TransactionType_Id])
REFERENCES [dbo].[Tbl_TransactionType] ([Fld_TransactionType_Id])
GO
ALTER TABLE [dbo].[Tbl_Transaction] CHECK CONSTRAINT [FK_Tbl_Transaction_Tbl_TransactionType]
GO
ALTER TABLE [dbo].[Tbl_User]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_User_Tbl_Person] FOREIGN KEY([Fld_Person_PersonId])
REFERENCES [dbo].[Tbl_Person] ([Fld_Person_Id])
GO
ALTER TABLE [dbo].[Tbl_User] CHECK CONSTRAINT [FK_Tbl_User_Tbl_Person]
GO
ALTER TABLE [dbo].[Tbl_UserRole]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_UserRole_Tbl_Role] FOREIGN KEY([Fld_Role_RoleId])
REFERENCES [dbo].[Tbl_Role] ([Fld_Role_Id])
GO
ALTER TABLE [dbo].[Tbl_UserRole] CHECK CONSTRAINT [FK_Tbl_UserRole_Tbl_Role]
GO
ALTER TABLE [dbo].[Tbl_UserRole]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_UserRole_Tbl_User] FOREIGN KEY([Fld_User_UserId])
REFERENCES [dbo].[Tbl_User] ([Fld_User_Id])
GO
ALTER TABLE [dbo].[Tbl_UserRole] CHECK CONSTRAINT [FK_Tbl_UserRole_Tbl_User]
GO
ALTER TABLE [dbo].[Tbl_UserSession]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_UserSession_Tbl_User] FOREIGN KEY([Fld_User_UserId])
REFERENCES [dbo].[Tbl_User] ([Fld_User_Id])
GO
ALTER TABLE [dbo].[Tbl_UserSession] CHECK CONSTRAINT [FK_Tbl_UserSession_Tbl_User]
GO
ALTER TABLE [dbo].[Tbl_Wallet]  WITH CHECK ADD  CONSTRAINT [FK_Tbl_Wallet_Tbl_Sim] FOREIGN KEY([Fld_Wallet_Id])
REFERENCES [dbo].[Tbl_Sim] ([Fld_Sim_Id])
GO
ALTER TABLE [dbo].[Tbl_Wallet] CHECK CONSTRAINT [FK_Tbl_Wallet_Tbl_Sim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ss_selectPeople]
AS
SELECT * FROM Tbl_Person WHERE Fld_Person_IsDeleted=0
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ss_selectPerson] @PersonId int
AS
SELECT * FROM Tbl_Person WHERE  Fld_Person_Id=@PersonId
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ss_selectPersonSimcards] @PersonId int
AS
SELECT * FROM Tbl_Sim WHERE  Fld_Person_Id=@PersonId
GO
USE [master]
GO
ALTER DATABASE [OperatorManagementDB] SET  READ_WRITE 
GO
